apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: mohammad1996/customer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://lin-22373-8009-pgsql-primary.servers.linodedb.net:5432/customer
            - name: SPRING_DATASOURCE_PASSWORD
              value: Y0rLVh-chFJa8Hqi
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer

