server:
  port: 8083
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud
          uri: lb://FRAUD
          predicates:
            - Path=/api/v1/fraud/**
        - id: champion
          uri: lb://CHAMPION
          predicates:
            - Path=/api/v1/champion/**
        - id: fraudchampion
          uri: lb://FRAUDCHAMPION
          predicates:
            - Path=/api/v1/fraudchampion/**
        - id: feed
          uri: lb://FEED
          predicates:
            - Path=/api/v1/feed/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
