apiVersion: apps/v1
kind: Deployment
metadata:
  name: champion
  labels:
    app: champion
spec:
  replicas: 1
  template:
    metadata:
      name: champion
      labels:
        app: champion
    spec:
      containers:
        - name: champion
          image: mohammad1996/champion:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://lin-22373-8009-pgsql-primary.servers.linodedb.net:5432/champion
            - name: SPRING_DATASOURCE_PASSWORD
              value: Y0rLVh-chFJa8Hqi
      restartPolicy: Always
  selector:
    matchLabels:
      app: champion
