apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraudchampion
  labels:
    app: fraudchampion
spec:
  replicas: 1
  template:
    metadata:
      name: fraudchampion
      labels:
        app: fraudchampion
    spec:
      containers:
        - name: fraudchampion
          image: mohammad1996/fraudchampion:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://lin-22373-8009-pgsql-primary.servers.linodedb.net:5432/fraudchampion
            - name: SPRING_DATASOURCE_PASSWORD
              value: Y0rLVh-chFJa8Hqi
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraudchampion
